### ISSUE TITLE
strange characters at the end of "Component-Example" url on pharo 12

### ISSUE THREAD

**Issue by git-dmou** [ErikOnBike/CodeParadise#24] opened 2024-01-16 08:17 UTC
when starting the "Component-Examples" application from code paradise menu, the browser open with an url ending with 2 random characters .... and of course, the loading never end.

when I remove these chars, to get a clean url, the application opens as expected.

I've tried all the applications from the menu and this is the only case of this strange behaviour.

**Comment by ErikOnBike** [comment] 2024-01-16 19:11
Hi @git-dmou

I'm really puzzled here. I tried the menu and all items work without a problem. Which Pharo version are you using and which VM version? I tried Pharo 10 and 12.

The code for the Component Examples does not seem special if compared to other applications.

Sunny regards,
Erik

**Comment by ErikOnBike** [comment] 2024-01-16 19:13
@git-dmou I see you're using Pharo 12 (didn't read the title carefully enough)...

**Comment by ErikOnBike** [comment] 2024-01-16 19:19
@git-dmou retried with new image, but still works.
Which OS are you on? No clue if this makes a difference, but seeing if I can reproduce this.

**Comment by git-dmou** [comment] 2024-01-17 10:35
Hello Erik,

I'm on windows 11, I've tried on 2 differents computers,

VM: 120-x64 2024-01-15 update

image pharo 12 from the same day

tried on chrome and Firefox.

I browsed the code quickly and saw no differences between apps in the building of url as you said !

**Comment by astares** [comment] 2024-01-17 10:45
Specific language setting on browser?

**Comment by git-dmou** [comment] 2024-01-17 10:57
I've tried english on firefox and french on chrome

**Comment by ErikOnBike** [comment] 2024-01-17 12:07
Which characters are appended? You wrote 'random'. Does this mean it differs between executions?
Could you try and add a breakpoint in `CpDevTools class >> #open` and inspect what the value of `choices` is before making the selection and what the value of `choice` is after making the selection? This to check whether these random characters are coming from the Pharo image or whether the browser (plugin?) somehow adds these characters.
Thx

**Comment by git-dmou** [comment] 2024-01-17 12:14
by random I mean a couple of different char at each exec.
for example : "À3" or "%10k" or "rš", appended to "http://localhost:8080/static/app.html?Component-Examples"

I'll try with the breakpoint

**Comment by git-dmou** [comment] 2024-01-17 12:19
<img width="950" alt="Capture d'écran 2024-01-17 131902" src="https://github.com/ErikOnBike/CodeParadise/assets/121164988/6a911c32-d6db-4c11-9817-b3c36d0a091a">

apparently, no problems so far !

**Comment by git-dmou** [comment] 2024-01-17 12:36
here you are 
![image](https://github.com/ErikOnBike/CodeParadise/assets/121164988/86c31eee-ab04-47ed-a861-e56974d68b54)

**Comment by git-dmou** [comment] 2024-01-17 12:36
your right, non random chars in the pharo area !

**Comment by ErikOnBike** [comment] 2024-01-17 12:40
Hmmm...that still leaves the FFI stuff (but it works for other applications, so what would make this one special?), since it behaves the same in both Chrome and Firefox.
Could you try and update the method `CpComponentExamplesWebApplication class >> #app` and replace the content with:
```
app

	"Answer the unique identifier (a Symbol) for the receiver"

	^ #fixmesoon
```
Do a 'reset' from the CodeParadise menu and try to run the application (now named 'fixmesoon').

**Comment by git-dmou** [comment] 2024-01-17 12:44
I tried like this : 
it seems that any name finishing in "example" trigger the problem !
![image](https://github.com/ErikOnBike/CodeParadise/assets/121164988/66bf8cb3-8609-46aa-bb31-7702ad0668c0)

**Comment by git-dmou** [comment] 2024-01-17 12:45
and it works !

**Comment by ErikOnBike** [comment] 2024-01-17 12:47
Not fully sure yet ;-).
Could you try and replace the method with this one:
```
app

	"Answer the unique identifier (a Symbol) for the receiver"

	^ #'Cmponent-Examples'
```
I made it a single character shorter, but still has the same 'ending'. I am wondering whether the final URL size (56 bytes/chars) is causing an issue. This is 2 longs (2x 4 bytes) short of 64 bytes, which might be some sort of magic size limit. 
Please let me know what happens.

**Comment by ErikOnBike** [comment] 2024-01-17 12:48
Remember that Soelace-Examples works okay, but also ends with '-Examples'.

**Comment by git-dmou** [comment] 2024-01-17 12:52
It works, it should be a length problem ....

**Comment by git-dmou** [comment] 2024-01-17 12:53
however, "building-my-first-app" is longer, but has no problem

**Comment by ErikOnBike** [comment] 2024-01-17 12:59
Maybe not every length. Could you try the following version? If this works, it is not perse the length. This is a version with the same length but different content. We're just trying to find the cause by taking away possibilities ;-)
```
app

	"Answer the unique identifier (a Symbol) for the receiver"

	^ #'Component-Examplex'
```

**Comment by ErikOnBike** [comment] 2024-01-17 13:00
Thx for helping out and testing these things out by the way! 🙏

**Comment by git-dmou** [comment] 2024-01-17 13:01
again:
http://localhost:8080/static/app.html?Component-Examplex%E2%82%AC/
http://localhost:8080/static/app.html?Component-Examplex%C3%9Es

**Comment by ErikOnBike** [comment] 2024-01-17 13:03
Okay. So it seems this specific length is an issue. I'm investigating a little here. I will try to come back with some more tests if you're okay with that.

**Comment by ErikOnBike** [comment] 2024-01-17 13:25
Could you give me the result of evaluating the following in a Playground?
```
#shell32 asFFILibrary calloutAPIClass
```
It should probably answer something like FFICalloutAPI or TFCalloutAPI.
It is either the regular or the threaded FFI version.

**Comment by git-dmou** [comment] 2024-01-17 13:28
TFCalloutAPI

**Comment by ErikOnBike** [comment] 2024-01-17 13:43
Could you please evaluate/inspect the following?
```
TFUFFIDerivedTypeMarshallingTest new
	ffiLibrary: TFTestLibraryUsingSameThreadRunner ;
	pointerToString: 'http://localhost:8080/static/app.html?Component-Examples'.
```
Does it answer the correct (duplicated) String or does it also have random characters added?
And this variant?
```
TFUFFIDerivedTypeMarshallingTest new
	ffiLibrary: TFTestLibraryUsingWorker ;
	pointerToString: 'http://localhost:8080/static/app.html?Component-Examples'.
```

**Comment by git-dmou** [comment] 2024-01-17 13:51
![image](https://github.com/ErikOnBike/CodeParadise/assets/121164988/329a3923-51bb-49ea-a9bd-f6069ac799d9)

<img width="810" alt="Capture d'écran 2024-01-17 144755" src="https://github.com/ErikOnBike/CodeParadise/assets/121164988/4beb998d-d464-4258-b408-0a7d27cf6373">

**Comment by ErikOnBike** [comment] 2024-01-17 15:18
Have dug deep into the code (into primitives and generated FFI code), but can't find the location where things go wrong. My feeling is it has to do with the FFI (Foreign Function Interface). I'll post a question on the Discord channel. Hopefully someone can help out. Thx so far and I will keep you updated.

**Comment by git-dmou** [comment] 2024-01-17 15:29
quite tricky !
the best thing to do so far on windows is to choose a name for the app and to test the generated url in the browser !

**Comment by ErikOnBike** [comment] 2024-01-18 15:38
@astares It seems the exact length is an issue. I also posted this on Discord (see link below).
Could you try the following on your machine as well?
```
WebBrowser openOn: 'https://pharo.org?abcdefghijklmnopqrstuvwxyz1234567890ok'.
```
https://discord.com/channels/223421264751099906/786544722235228160/1197203535285211166

**Comment by astares** [comment] 2024-01-18 15:51
Seems to be Pharo related as on DOS it works without additional characters

<img width="446" alt="image" src="https://github.com/ErikOnBike/CodeParadise/assets/5980033/9624f76d-a29e-4331-8c3d-a134afc2f3eb">

**Comment by astares** [comment] 2024-01-18 15:52
> @astares It seems the exact length is an issue. I also posted this on Discord (see link below). Could you try the following on your machine as well?
> 
> ```
> WebBrowser openOn: 'https://pharo.org?abcdefghijklmnopqrstuvwxyz1234567890ok'.
> ```
> 
> https://discord.com/channels/223421264751099906/786544722235228160/1197203535285211166

<img width="217" alt="image" src="https://github.com/ErikOnBike/CodeParadise/assets/5980033/2f41923a-b5b5-4da5-9cdd-98009c93b8c5">

**Comment by astares** [comment] 2024-01-18 16:08
opened https://github.com/pharo-project/pharo/issues/15980 as it is more Pharo related than a Code paradise issue

**Comment by denysos** [comment] 2024-03-03 09:24
Hello Erik,
it seems that this issue is fixed with

Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1410.sha.6fa4632c0b60f6690d6af3f7f8fc6f3ab6240112 (64 Bit)

after the UFFI issue https://github.com/pharo-project/pharo/issues/15980 fixed

**Comment by ErikOnBike** [comment] 2024-03-04 06:53
@denysos Thx.
@astares for the fix!
Closing the issue.

**Closed by ErikOnBike** 2024-03-04 06:53 UTC
